import React from 'react';
import { Destination } from '../types';
import { X, MapPin, Mountain, CloudSun, Navigation, Calendar, Footprints, Star } from 'lucide-react';

export const DestinationDetailModal: React.FC<{ destination: Destination; isOpen: boolean; onClose: () => void; onOpenWeather: (destination: Destination) => void; onOpenMap: (destination: Destination) => void }> = ({ destination, isOpen, onClose, onOpenWeather, onOpenMap }) => {
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 bg-[#1E2822]/80 backdrop-blur-sm p-3 sm:p-6 flex items-center justify-center"><div className="w-full max-w-3xl max-h-[92vh] overflow-y-auto bg-[#FDFCF7] rounded-3xl shadow-2xl">
    <div className="relative h-64 sm:h-80"><img src={destination.coverImage} alt={destination.name} className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1E2822] via-transparent" /><button onClick={onClose} className="absolute top-4 right-4 p-2 rounded-xl bg-black/40 text-white"><X /></button><div className="absolute bottom-5 left-6 text-white"><span className="text-xs font-bold uppercase tracking-wider bg-[#4A6741] px-2 py-1 rounded-full">{destination.type === 'fort' ? '🏰 Fort' : '🥾 Trek'}</span><h2 className="font-heading text-3xl font-extrabold mt-3">{destination.name}</h2><p className="text-sm flex gap-1 items-center"><MapPin className="w-4 h-4" />{destination.district}, {destination.state}</p></div></div>
    <div className="p-6 space-y-6"><p className="text-sm leading-relaxed text-[#5C6662]">{destination.description}</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">{destination.altitudeM && <Metric icon={<Mountain />} label="Altitude" value={`${destination.altitudeM.toLocaleString()} m`} />}{destination.durationDays && <Metric icon={<Calendar />} label="Duration" value={`${destination.durationDays} day${destination.durationDays > 1 ? 's' : ''}`} />}{destination.distanceKm && <Metric icon={<Footprints />} label="Distance" value={`${destination.distanceKm} km`} />}{destination.rating && <Metric icon={<Star />} label="Rating" value={`${destination.rating}/5`} />}</div>{!!destination.highlights?.length && <div><h3 className="font-heading font-bold mb-2">Highlights</h3><div className="flex flex-wrap gap-2">{destination.highlights.map(h => <span key={h} className="text-xs bg-[#F3F1EA] border border-[#E8E4D9] rounded-lg px-2.5 py-1.5">{h}</span>)}</div></div>}<div className="flex flex-wrap gap-3 pt-2"><button onClick={() => onOpenWeather(destination)} className="px-4 py-2.5 rounded-xl border border-[#4A6741]/30 text-[#2D4F1E] font-bold text-xs flex gap-2 items-center"><CloudSun className="w-4 h-4" />Live Weather</button><button onClick={() => onOpenMap(destination)} className="px-4 py-2.5 rounded-xl bg-[#4A6741] text-white font-bold text-xs flex gap-2 items-center"><Navigation className="w-4 h-4" />Get Directions</button></div></div>
  </div></div>;
};
const Metric = ({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) => <div className="bg-[#F3F1EA] rounded-xl p-3 text-[#5C6662]"><div className="w-4 h-4 text-[#4A6741] mb-1">{icon}</div><div className="text-[10px] uppercase font-bold">{label}</div><div className="font-bold text-[#2D3633]">{value}</div></div>;
